<!doctype html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <?php $this->assets->outputCss('header') ?>
    <title>图片管理系统</title>
</head>
<body class="container">
<div class="row">
    <aside class="col-md-4 visible-md-block visible-lg-block pull-left">
        <div class="form-group">
            <label for="search-image-mane" class="from-control-static">关键词搜索：</label>
            <input type="text" id="search-image-mane" class="form-control" placeholder="请输入关键词">
        </div>
        <h2>
            <button class="btn btn-default" id="conditions-search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> 高级搜索</button>
            <button class="btn btn-default" id="game-tree-list"><span class="glyphicon glyphicon-back" aria-hidden="true"></span> 返回赛程列表</button>
        </h2>
        <br>
        <div class="sr-only" id="aside-tree">
            <section id="labels" class="tags-label" data-api="<?= $url->get('ims_labels') ?>"></section>
            <nav>
                <div id="tree" data-api="<?= $url->get('ims_games') ?>"></div>
            </nav>
        </div>
        <div id="aside-search">
            <form id="search">
                <br>
                <input type="text" id="search-start-time" class="sr-only">
                <input type="text" id="search-end-time" class="sr-only">
                <br>
                <div class="form-group">
                    <label for="search-football-tags" class="from-control-static">足球标签：</label>
                    <input type="text" id="football-search" class="form-control sr-only" placeholder="不限">
                    <div class="panel-body tags-label" id="football-tags-search" style="display:block;"></div>
                </div>
                <br>
                <div class="form-group">
                    <label for="search-nba-tags" class="from-control-static">篮球标签：</label>
                    <input type="text" id="nba-search" class="form-control sr-only" placeholder="不限">
                    <div class="panel-body tags-label" id="nba-tags-search" style="display:block;"></div>
                </div>
            </form>
        </div>
    </aside>
    <div class="col-md-8 col-sm-12 col-xs-12 pull-right">
        <section>
            <h2 class="row">
                <span class="col-md-2 col-sm-2 col-xs-3">
                    <input type="file" id="images-upload" multiple accept="image/jpeg,image/png,image/gif,image/bmp" style="display: none">
                    <button class="btn btn-block btn-primary">上传</button>
                </span>
                <span class="col-md-2 col-sm-2 col-xs-3">
                    <button class="btn btn-block btn-primary shaixuan" data-month="1">一个月</button>
                </span>
                <span class="col-md-2 col-sm-2 col-xs-3">
                    <button class="btn btn-block btn-primary shaixuan" data-month="3">三个月</button>
                </span>
                <span class="col-md-2 col-sm-2 col-xs-3">
                    <button class="btn btn-block btn-primary shaixuan" data-month="12">一年</button>
                </span>
                <span class="col-md-2 col-sm-2 col-xs-3">
                    <button class="btn btn-block btn-primary shaixuan" data-month="0">全部</button>
                </span>
            </h2>
            <hr>
            <div style="display: none" id="new3games">
                <label for="">最新3场比赛：</label>
                <button class="btn btn-sm"></button>
                <button class="btn btn-sm"></button>
                <button class="btn btn-sm"></button>
            </div>
            <br>
            <div id="images-wall" class="row" data-api="<?= $url->get('ims_images') ?>"></div>
            <h3 id="is-loaded" class="text-center text-warning"></h3>
        </section>
    </div>
</div>
<!-- 模态框（Modal） -->
<div class="modal fade" id="image-editor" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">编辑图片信息</h4>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" id="image-game_id">
                    <input type="hidden" id="image-id">
                    <div class="form-group row">
                        <div class="col-md-2 col-sm-2 col-xs-3 text-right">
                            <label for="image-name" class="form-control-static">名称</label>
                        </div>
                        <div class="col-md-10 col-sm-10 col-xs-9">
                            <input type="text" id="image-name" class="form-control" placeholder="支持输入图片名称，必填，1~50个汉字">
                        </div>
                    </div>
                    <div class="form-group row" id="tags" data-api="<?= $url->get('ims_tags') ?>">
                        <div class="col-md-2 col-sm-2 col-xs-3 text-right">
                            <label for="tags-editor" class="form-control-static">标签</label>
                        </div>
                        <div class="col-md-10 col-sm-10 col-xs-9">
                            <input type="text" id="tags-editor">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-offset-2 col-md-10 col-sm-offset-2 col-sm-10 col-xs-offset-3 col-xs-9">
                            <div class="panel panel-default">
                                <div class="panel-body tags-label" id="nba-tags-label" style="display: none"></div>
                                <div class="panel-body tags-label" id="football-tags-label" style="display: none"></div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" id="update-image" class="btn btn-primary" data-dismiss="modal">提交更改</button>
            </div>
        </div>
    </div>
</div>
<!-- 模态框（Modal） -->
<div class="modal fade" id="upload-modal" tabindex="-1" role="dialog" aria-labelledby="UploadModal" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">上传</h4>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="finish btn btn-primary" data-dismiss="modal" aria-hidden="true">完成</button>
            </div>
        </div>
    </div>
</div>
<?php $this->assets->outputJs('footer') ?>
</body>
</html>